### PR TITLE
add delete function

### PR DESCRIPTION
**Pull request by LQBing**

### CODE REVIEW

**Comment by momocow** [comment]
Hi, I just happened to see this PR and come up with a question.

How is `delete()` different from `filter()` given the filter function is `lambda d: True`?

```
>>> jsonpath_expr = parse("foo[*].baz")
>>> jsonpath_expr.filter(lambda d: True, {'foo': [{'baz': 1}, {'baz': 2}]})
{'foo': [{}, {}]}
```

**Comment by LQBing** [comment]
Verified

> Hi, I just happened to see this PR and come up with a question.
> 
> How is `delete()` different from `filter()` given the filter function is `lambda d: True`?
> 
> ```
> >>> jsonpath_expr = parse("foo[*].baz")
> >>> jsonpath_expr.filter(lambda d: True, {'foo': [{'baz': 1}, {'baz': 2}]})
> {'foo': [{}, {}]}
> ```
I verified, no different between their result. 
But it is not easy to find this usage in the readme.md, and the delete or remove function is a common methods. Can you add the usage into the readme.md?

**Comment by momocow** [comment]
> Can you add the usage into the readme.md?

Sorry but no, I'm not even the owner or a contributor of this repo, just someone trying to figure out how to do filtering with jsonpath.

But I think #44 may be useful to you.

**Comment by michaelmior** [comment]
I added some relevant examples to the README, so I think this can be closed. Feel free to comment if you're still having any issues.

**Pull request closed without merging**
