### PR TITLE
Fix invalid escape sequences in strings.

### LINKED ISSUE #33: Deprecation warning due to invalid escape sequences in Python 3.8
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Walways -m py_compile {}

./jsonpath_ng/ext/string.py:18: DeprecationWarning: invalid escape sequence \(
  SUB = re.compile("sub\(/(.*)/,\s+(.*)\)")
./jsonpath_ng/ext/string.py:19: DeprecationWarning: invalid escape sequence \(
  SPLIT = re.compile("split\((.),\s+(\d+),\s+(\d+|-1)\)")
./tests/test_jsonpath_rw_ext.py:129: DeprecationWarning: invalid escape sequence \c
  ('sort2', dict(string='objects[\cat]',
./tests/test_jsonpath_rw_ext.py:132: DeprecationWarning: invalid escape sequence \c
  ('sort2_indexed', dict(string='objects[\cat][-1].cat',
./tests/test_jsonpath_rw_ext.py:136: DeprecationWarning: invalid escape sequence \c
  ('sort3', dict(string='objects[/cow,\cat]',
./tests/test_jsonpath_rw_ext.py:145: DeprecationWarning: invalid escape sequence \c
  ('sort3_indexed', dict(string='objects[/cow,\cat][0].cat',
```

### PR DESCRIPTION
**Pull request by domdfcoding**
For the tests I've used double back slashes, as some of the strings had them already. For the regular expressions in `string.py` I've used raw strings as there are more back slashes in each string.

Fixes #33

### CODE REVIEW

**Comment by domdfcoding** [comment]
👈 Friendly ping

**Comment by ciwasaki** [comment]
seconding the friendly ping!

**Comment by RoaldO** [comment]
third friendly ping

**Review by kurtmckee — APPROVED** [review]
@h2non Please merge this PR.

It's needed to resolve errors when Python code is running with warnings escalated to errors (e.g. `python -W error`).

**Pull request merged**
