### PR TITLE
Improve Split regex

### PR DESCRIPTION
**Pull request by smartycope**
Added negative and * indecies and quotes to Split parameters

### CODE REVIEW

**Comment by michaelmior** [comment]
Could you clarify what the purpose is of the changes to the split regex?

**Comment by smartycope** [comment]
It does a few things:

- Allows you to split on spaces and commas by using quotes
- Allows for negative indexing on the split
- Allows you to return all the split items as a list, instead of having to select a specific index
- The regex now allows for optional whitespace between the arguments (just to make the extension a little more pythonic)

**Comment by michaelmior** [comment]
@smartycope Thanks! I think it would help to have pieces of the regex documented in the code since it's non-trivial to understand.

I'm also curious why you used `(?:\s+)?` instead of `(?:\s*)`. Is there some subtle difference I'm missing?

**Comment by smartycope** [comment]
@michaelmior I added the documentation you asked for, good thinking. 

As for `(?:\s+)?` vs `(?:\s*)`, I don't know of a difference, that's simply how it was generated.

**Comment by michaelmior** [comment]
LGTM, thanks!

**Pull request merged**
